Vue.component('deliver-history', require('./deliver-history.vue'))
Vue.component('storage-list', require('./storage-list.vue'))
Vue.component('order-history', require('./order-history.vue'))
Vue.component('news-list', require('./news-list.vue'))
Vue.component('order-dialog', require('./order-dialog.vue'))
Vue.component('game-clock', require('./game-clock.vue'))
Vue.component('storage-register-dialog', require('./storage-register-dialog.vue'))
Vue.component('deliver-dialog', require('./deliver-dialog.vue'))
Vue.component('online-status', require('./online-status.vue'))
Vue.component('info-panel', require('./info-panel.vue'))
Vue.component('account-dialog', require('./account-dialog.vue'))
Vue.component('msg-dialog', require('./msg-dialog.vue'))
Vue.component('market-info', require('./market-info.vue'))
Vue.component('team-storage-list', require('./team-storage-list.vue'))
Vue.component('team-deliver-avaliable-list', require('./team-deliver-avaliable-list.vue'))
// Vue.component('news-publisher-dialog', require('./news-publisher-dialog.vue'))

// Discarded:
// Vue.component('received-order', require('./received-order.vue'))
// Vue.component('line-chart', require('./line-chart.vue'))
